# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'solution' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for solution
	pod 'GoogleMaps'
	pod 'GooglePlaces'
    pod 'Firebase/Database'
    pod 'Kingfisher'
    pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
    pod 'TweenKit', '~> 0.2.1'

  target 'solutionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'solutionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
